### ISSUE TITLE
Snapshot parameter "snapshot-is-optional" doesn't work

### ISSUE THREAD

**Issue by jvce** [akka/akka-persistence-dynamodb-1.x#108]
### Versions used 

akka-persistence-dynamodb version: 1.1.1

### Expected Behavior

The page https://doc.akka.io/docs/akka/current/persistence.html#optional-snapshots describes that it is possible to configure the snap shot store to ignore snapshots that fail to deserialize. This uses the configuration parameter "snapshot-is-optional". 
When a snapshot fails to deserialize, the snapshot would be ignored and the actor would recover from all events in the source if that parameter is set to true.

### Actual Behavior

I tried to use this with deserializer that always fails and persistence just completely fails, instead of building from events as the page describes.

The use case is that if our state building changes over time, we would include a version parameter in the snapshot and fail the deserialization for versions that are different from the last. This is quite an important step to be able to be backwards compatible.

To be sure, I checked [DynamoDBSnapshotConfig.scala](https://github.com/akka/akka-persistence-dynamodb/blob/master/src/main/scala/akka/persistence/dynamodb/snapshot/DynamoDBSnapshotConfig.scala) and the parameter is indeed not listed there.

### Proposed solution
The solution can be quite elegant. I would adapt the load function of [DynamoDBSnapshotRequests.scala](https://github.com/akka/akka-persistence-dynamodb/blob/master/src/main/scala/akka/persistence/dynamodb/snapshot/DynamoDBSnapshotRequests.scala) . I would surround the Some case with a try catch that just returns a None if the configuration parameter is set to true and otherwise just forwards the Exception.

**Comment by coreyoconnor** [comment]
Thanks for the bug report!

**Comment by jvce** [comment]
This was a false report!

We are stuck on Akka-Persistence 2.5.32. The snapshot-is-optional was introduced in Akka-Persistence 2.6.15.
https://github.com/akka/akka/issues/30234

So the solution for the problem has nothing to do with the DynamoDB Driver 🤦
