### ISSUE TITLE
Errors after upgrade to 1.1.2

### ISSUE THREAD

**Issue by jillguyonnet** [akka/akka-persistence-dynamodb-1.x#109]
## Description

Akka version: 2.6.18
Previously used akka-persistence-dynamodb version: 1.2.0-SNAPSHOT
akka-persistence-dynamodb version with issue: 1.1.2
Reason for upgrade: address performance issues (cf. https://github.com/akka/akka-persistence-dynamodb/pull/107)

## Issue description

Many errors encountered trying out version 1.1.2 on our staging environment.

Examples errors:

```
software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Response entity was not subscribed after 1 second. Make sure to read the response `entity` body or call `entity.discardBytes()` on it -- in case you deal with `HttpResponse`, use the shortcut `response.discardEntityBytes()`. POST / Default(96 bytes) -> 200 OK Default(1558126 bytes)
```

```
Error while processing signal [RecoveryFailed(akka.persistence.typed.internal.JournalFailureException: Exception during recovery. Last known sequence number [0]. PersistenceId [agent|1996375#4560623845501], due to: Circuit Breaker Timed out.)]: akka.persistence.typed.internal.JournalFailureException: Exception during recovery. Last known sequence number [0]. PersistenceId [agent|1996375#4560623845501], due to: Circuit Breaker Timed out.
```

## Additional information

No issues encountered trying this version in a local development environment.

The staging database is populated with old data that cannot be deleted.

**Comment by rmmeans** [comment]
I can try to take a look hopefully next week. It has been more than 6 months since I worked on this so I don't have a quick answer. I may reach out with some more questions after I dig a little. Thanks!!

**Comment by coreyoconnor** [comment]
Is this with `dynamodb-journal.fixes.high-distrust = true` in the config?

**Comment by coreyoconnor** [comment]
Also: Can you increase logging to `debug` and post the `akka.persistence` log messages during startup up until this failure?

**Comment by jillguyonnet** [comment]
Finally got a chance to come back to this. We were not able to reproduce the issue on our staging environment, so my guess is there might have been an issue with in in June. We're running the new version now.

Closing this ticket, thanks folks.
