### ISSUE TITLE
release 1.3.0

### ISSUE THREAD

**Issue by coreyoconnor** [akka/akka-persistence-dynamodb-1.x#116]
Tracking ticket for release of 1.3.0.

The tag is already created for 1.3.0. If there is an issue with the current code blocking 1.3.0 then update, add 1.3.1 tag, then release.

Pinging @johanandren for visibility :)

**Comment by johanandren** [comment]
I'll do a release 👍

**Comment by johanandren** [comment]
On its way to maven central

**Comment by coreyoconnor** [comment]
Thanks!
