### ISSUE TITLE
Does it make sense to try to retain storage compatibility with Akka <= 2.3.3?

### ISSUE THREAD

**Issue by rkuhn** [akka/akka-persistence-dynamodb-1.x#13]
With the removal of Channels and confirmations there are actual features that cannot any longer be expressed, meaning that the application code itself will have to change.

@patriknw @ktoso @sclasen what is your opinion?

**Comment by sclasen** [comment]
+1 to not attempting to retain compatibility, the underlying layout will have to change to reflect the updated functionality in akka-persistence

**Comment by rkuhn** [comment]
Okay, then we’re going for a 1.0 version that clearly advertises no compatibility to 0.x versions.

**Comment by patriknw** [comment]
+1 for making a clean cut, but if there are tooling around DynamoDB that makes it possible to do a ETL migration it is good to mention the possibility in some migration guide

**Comment by rkuhn** [comment]
Good, that’s settled then. Filed #21 for the migration guide.
