### ISSUE TITLE
proposal for more efficient replays

### ISSUE THREAD

**Issue by rkuhn** [akka/akka-persistence-dynamodb-1.x#14]
The current scheme tries to avoid hot partition keys by going to the far end of the spectrum: every event is stored separately. It might be better to colocate contiguous parts of the log up to a given size, say 1000 events. This means that the partition key should include `sequenceNr / 1000` and within that a sort key is used that reads `sequenceNr % 1000`. This allows the lowest and highest sequence number to be stored in a central item since it only needs to be updated every 1000 events—the precise value is then assembled by a read of this item and a query of the partition it points to.

@sclasen WDYT?

This can of course only be implemented if the answer to #13 is “no”.

**Comment by sclasen** [comment]
I like the idea, one thing to consider is the limit on the size of dynamodb items is 400K,  (was 32k when the original code was written). So depends on what constraints if any can be placed on the size of Events. Worst case you would even have to stripe a single event across multiple dynamo items, if supporting events bigger than ~400k is important.

Even updating a single key every 1000 events, if you are writing at say 30,000/sec is likely enough to induce hot keys.

So, good line of thought, would just need to figure out the correct balance of tensions between being able to read fast and write fast.

I tend to think optimizing for fast writes is more important here, the bulk of read throughput should come from reading a snapshot from s3 (not yet implemented of course), then topping it off with as few reads as possible from dynamo.

**Comment by rkuhn** [comment]
Hmm, not sure we are talking about the exact same thing here: I mean to represent every event as a single item (with the 400kB size restriction) and updating the highest-sequence counter only every 100th (or so). This means that 100 consecutive events will go to the same partition, but I hope that that should work out fine—if one actor really generates 30,000/sec then that means touching 300 partitions/sec as well, which sounds not so hot to me :-)

One further thought here is that this reduces the write costs by roughly a factor of two since it requires only 1.01 writes per event instead of the current 2.

**Comment by sclasen** [comment]
Oh, gotcha!  Yes if that is within what is feasible given the journal contract then sounds good.  Write less. Whatever batching is possilbe you should do, a single BatchWriteItem can write 25 items.  Edit: oops, you cant update items with BatchWrite, so that needs to be a put item.

To note, you could use up to 100 sequence shards and retrieve them with a single BatchGetItem call, so  a hybrid approach is possible too.

**Comment by rkuhn** [comment]
This is more complicated than I thought, here’s my current battle plan (to be revisited tomorrow morning with a fresh mind):
- assumption: write requests come into the journal in strictly serialized fashion for any given persistenceId (but see akka/akka#19694 for the problems)
- add an attribute `brc` (batchRemainingCount) which signals how many of the following sequence numbers belong to the same AtomicWrite
- add a sort key that ranges from 0 to 99 and clip the last two digits off the partition key
- writing across a 99/0 transition MUST proceed like the following:
  - first await successful completion of the write to nr 99
  - then write and await the SH record, containing the next seqNr
  - then proceed with further (batched) writes into the new partition
- reading the highest sequence number will in addition to reading the 100th parts have to scan the maximally indicated partition for events, treating missing pieces of an AtomicWrite as empty but taken (since we cannot delete or overwrite items)
- during replay each AtomicWrite needs to be reassembled, and dropped if incomplete

It might also be possible to delete incomplete AtomicWrites during replay, but I cannot currently convince myself that that is actually safe in all scenarios.

There is one thing I am uncomfortable with: if in a sequence of writes some succeed and some do not, then the log may have random holes that may well leave the actor in an inconsistent state after having used persistAsync even if it decides to crash—the persisted events may result from actions that depended on the non-persisted ones. This should be more clearly documented in Akka, I think.

**Comment by sclasen** [comment]
heh, figured this was the source of the akka issue ;)

I wonder if we can look at the event items as a write-ahead log, and the sequence number as a commit log/high water mark of sorts.

write the events in parallel as fast as possible, and then only write the sequence number where we have a contiguous sequence of event writes acknowledged. And then only ack the writes back to the client when a sequence number larger then their own has been acked.

Doing the right thing with the sequence sharding is of course important, as you state above.

Pardon if you've already thought this through and found reason to dismiss it!

**Comment by rkuhn** [comment]
One thing I’m trying to avoid is that the behavior devolves into two writes per event for “slow” updating actors—because that has severe cost impact on DynamoDB.

**Comment by sclasen** [comment]
Gotcha, that is a good goal. I think it would take many persistent actors of that shape to have a big impact.  

Is there a particular density that is considered 'normal'?   Do users typically have thousands or more of these shape?  Or if not that what is your strawman for what the journal should support?

**Comment by sclasen** [comment]
also, shouldn't it be possible to coalesce the writes from all these low throughput actors together? 1 BatchWrite per 25 events (from up to 25 actors), and then btw 1 and 25 parallel writes for each actor's sequence? Maybe you are already assuming that.

Preferring to write events for a fewer number of actors where possible of course. Worst case is 26 writes, best case 2? 

Im (handwavingly :smile:  ) assuming it wouldn't be too difficult to stitch together the proper flow graphs to achieve the best available yields for whatever the 'flush window' is...

**Comment by patriknw** [comment]
> coalesce the writes from all these low throughput actors together

That is something I would like to do on the akka side some time. Currently the Seq of messages in `asyncWriteMessages` is always of size 1 when using `persist`, it should be be possible to batch writes from different persistenceId into the same call.

Some journals does not benefit from this though, e.g. Cassandra (as far as I know).

**Comment by rkuhn** [comment]
For DynamoDB such cross-persistenceId batching would actually be quite some coding effort for no gain (under the optimizations discussed here).
