### ISSUE TITLE
keep track of all persistenceIds that have data in the journal

### ISSUE THREAD

**Issue by rkuhn** [akka/akka-persistence-dynamodb-1.x#28]

**Comment by coreyoconnor** [comment]
One option for an implementation of this is a global secondary index with a hash key on persistence ID projecting only the key. 

Customers can pursue the GSI implementation with the current schema. Including this in the plugin is, effectively, the same request as #50.  The `persistenceIds` and `currentPersistenceIds` of a query provider would satisfy this.
