### ISSUE TITLE
allow the AWS client to find its own credentials

### ISSUE THREAD

**Issue by rkuhn** [akka/akka-persistence-dynamodb-1.x#45]
currently the credentials are set to empty strings when not configured, preventing the AWS client to look for keys in its environment

**Comment by sclasen** [comment]
it would probably be nice to asssure the journal can pick up credentials from the ec2 metadata api via
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/?com/amazonaws/auth/InstanceProfileCredentialsProvider.html

**Comment by rkuhn** [comment]
The recommendation is to not provide credentials at all, which means using the [default provider](http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html#using-the-default-credential-provider-chain). My plan is to take this route when the credentials found in the config are empty strings.

**Comment by sclasen** [comment]
:+1:
