### ISSUE TITLE
Akka 2.5 support

### ISSUE THREAD

**Issue by nemccarthy** [akka/akka-persistence-dynamodb-1.x#58]
Hi,

Could we add Akka 2.5 support? 

Cheers

**Comment by patriknw** [comment]
Doesn't it work if you override the dependencies to 2.5.2? Make sure that you also specify akka-stream 2.5.2.

Since 2.5 is binary backwards compatible with 2.4 it should work unless we have accidentally used any internal api here. This does not have dependency to persistence-query.

**Comment by ktoso** [comment]
It will just work, as Patrik described - I've added it to the readme.
