### ISSUE TITLE
Problem configuring snapshot store

### ISSUE THREAD

**Issue by nielsbergsma** [akka/akka-persistence-dynamodb-1.x#66]
Hi, 

I tried to configure the snapshot store within my project but I receive the following error during restore `Caused by: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Consistent reads are not supported on global secondary indexes.`

How can I resolve this?

**Comment by teroxik** [comment]
Not sure this is still active but feels like you have configured the snapshot store to use global index instead of the snapshot table. Closing for now.
