### ISSUE TITLE
Plugin Future

### ISSUE THREAD

**Issue by teroxik** [akka/akka-persistence-dynamodb-1.x#79]
Is anyone actively using this version of the plugin and interested in contributing further.

I'm currently working on adding support for async serializers for the plugin in a similar manner as it's done in the akka-persistence-cassandra. It would potentially break the backwards compatibility what's the best course of action? A migration would be required I suppose long term, short term code can handle both formats as the ddb is schema-less.

Other pain points:
* Support for AWS SDK 2.0 - fully async
* Missing Query Plugin

There is new ddb plugin implementation, with slightly different sharding and querying philosophy and https://github.com/j5ik2o/akka-persistence-dynamodb but with most of the missing bits implemented.

**Comment by johanandren** [comment]
Note that the only reason for having the async serializers is to be able to use the commercial lightbend GDPR support for persistence (https://developer.lightbend.com/docs/akka-commercial-addons/current/gdpr/index.html) with the journal.

**Comment by teroxik** [comment]
So that's good to be able to use the commercial GDPR plugin with this plugin, isn't it? Honestly it is actually the reason for adding the async serializer support. Even though it's risky as it is only community supported. Just trying to gauge if anyone is using it and has appetite to push it a bit further.

**Comment by coreyoconnor** [comment]
I'm definitely interested in keeping the dynamodb plugin sustained and improved. Willing to offer at least review and triage support.

**Comment by patriknw** [comment]
The core Akka team is not actively maintaining this project and community is welcome to evolve and improve it. Adding support for async serializers is welcome.  We were able to do that in Cassandra plugin without breaking compatibility.

**Comment by teroxik** [comment]
Could I get some feedback of the evolution of the schema. I went for keeping the old payload field for storing the `PersistentRepr` envelope and storing the event data in a separate field.  Just looking into the possibility of denormalizing the data even more, putting rest of the fields from PersistentRepr in each record as in the cassandra journal - writerUUID, persistence_id, sequence_nr, event_manifest - maybe swapping the event_manifest and ser_manifest.

**Comment by coreyoconnor** [comment]
Hi @teroxik 

Could I get a pointer to the branch with the sachema changes? Is that in #80 ?

**Comment by teroxik** [comment]
Hi @coreyoconnor, yes it is. I have to update the Readme, but it should be clear what's being done in the PR description in terms of schema.

**Comment by coreyoconnor** [comment]
@teroxik thanks! I will review next week. :)

**Comment by coreyoconnor** [comment]
I think we've established the current state: the project is community maintained; there are community members who can do maintenance.

Resolving :) please re-open if there open questions I'm missing
