### ISSUE TITLE
Cross build for Scala 2.13

### ISSUE THREAD

**Issue by esamson** [akka/akka-persistence-dynamodb-1.x#88]
### Short description

A release for Scala 2.13 would be nice to have.

### Details

I gave it a quick peek and it seems it would be a minor patch to get things to compile for 2.13. One usage of `conforms` and a couple of places where `Seq` bumps into mutable Buffer converted from Java.

**Comment by coreyoconnor** [comment]
This was indeed a minor patch! Resolved with #91 

thanks!
